### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by farishkash** [Chaia81/prj-rev-bwfs-dasmoto#2]
https://github.com/Chaia81/prj-rev-bwfs-dasmoto/blob/80d1129c9c42684dd2006f0c40ee4c6e5efe6629/Dasmoto/resources/style.css#L1-L6

When you are using the same font family for the whole site you can just use body to simplify it.

**Comment by Chaia81** [comment]
Oh, yea. Forgot about that. Thank you :)
